server.port=${PORT:8080}

spring.datasource.url=jdbc:${DATABASE_PUBLIC_URL:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${PGUSER:myuser}
spring.datasource.password=${PGPASSWORD:secret}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.docker.compose.enabled=false