server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# And on Railway add the variable:

# SPRING_PROFILES_ACTIVE=prod
spring.docker.compose.enabled=false
